name: vessel_boost_ci

channels:
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - numpy==1.26.4
      - torch==2.10.0+cpu
      - scipy==1.15.2
      - scikit-image==0.25.2
      - requests==2.32.5
      - nitransforms==24.1.4
      - matplotlib==3.8.4
      - tqdm==4.64.1
      - nibabel==5.2.1
      - torchio==0.20.19
      - patchify==0.2.3
      - antspyx==0.4.2
      - connected-components-3d==3.13.0
      - dynamic-network-architectures==0.4.3
      - huggingface_hub==1.27.0
