name: docker test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - README.md
      - .github/workflows/test_docker.yml
      - tests/test_docker.sh
      - tests/ci_helpers.sh

  pull_request:
    branches: [ master ]
    paths:
      - README.md
      - .github/workflows/test_docker.yml
      - tests/test_docker.sh
      - tests/ci_helpers.sh

permissions:
  contents: read

jobs:
  test_docker_pipeline:
    runs-on: ubuntu-latest
    container: 
      image: vnmd/vesselboost_2.0.0:latest
      volumes:
        - /home/runner/:/home/
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      # ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
      # ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
      HF_TOKEN: ${{ github.event_name == 'push' && secrets.HF_TOKEN || '' }}
      PUBLISH_CI_RESULTS: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v3
    - name: test docker container
      run: |
        /bin/bash tests/test_docker.sh
