name: prediction module test

on:
  push:
    branches: [ master ]
    paths:
      - README.md
      - prediction.py
      - config/pred_config.py
      - environment.yml
      - environment-ci.yml
      - documentation/UPDATE.md
      - documentation/predict_readme.md
      - library/aug_utils.py
      - library/data_loaders.py
      - library/eval_utils.py
      - library/loss_func.py
      - library/module_utils.py
      - library/train_utils.py
      - tests/test_prediction_module.sh
      - tests/ci_helpers.sh
      - miniconda-setup.sh
      - .github/workflows/test_prediction.yml

  pull_request:
    branches: [ master ]
    paths:
      - README.md
      - prediction.py
      - config/pred_config.py
      - environment.yml
      - environment-ci.yml
      - documentation/UPDATE.md
      - documentation/predict_readme.md
      - library/aug_utils.py
      - library/data_loaders.py
      - library/eval_utils.py
      - library/loss_func.py
      - library/module_utils.py
      - library/train_utils.py
      - tests/test_prediction_module.sh
      - tests/ci_helpers.sh
      - miniconda-setup.sh
      - .github/workflows/test_prediction.yml

permissions:
  contents: read

jobs:
  test_prediction_module_pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.10.16
    - name: test prediction module
      env:
        HF_TOKEN: ${{ github.event_name == 'push' && secrets.HF_TOKEN || '' }}
        PUBLISH_CI_RESULTS: ${{ github.event_name == 'push' }}
      run: |
        /bin/bash tests/test_prediction_module.sh
